### ISSUE TITLE
[DIFFERENT ISSUE] Mod Porting Permissions

### ISSUE THREAD

**Issue by PulseBeat02** [ACGaming/acgaming.github.io#1]
Hi, there is a mod called "Custom CutScenes/SplashScreens" (https://www.curseforge.com/minecraft/mc-mods/custom-cutscenes-splashscreen) that you created in 1.8.9 a couple years ago. Because I really wanted to have a similar mod in 1.12.2, do I have permission to port the mod to higher Minecraft versions? The reason why I am asking is because the work is listed as "All Rights Reserved", so I must ask first before i can touch the code. Thank you.

**Comment by ACGaming** [comment]
I only did the German localization for that mod. Feel free to ask @GenDeathrow!

**Comment by PulseBeat02** [comment]
Ah, I see. Thank you for your reply! I will ask him.
